//=============================================================================
// Schach - Parsing
//=============================================================================

/*:
 *
 * @target MZ
 * @plugindesc Parsing core library.
 * @author Brandt
 * 
 * @url https://github.com/comuns-rpgmaker/schach-parsing
 * 
 * @help Schach Parsing.
 * 
 * This is a core library for expression parsing. This script does not provide
 * any functionality by itself, only functions that ought to be used by other
 * scripts to make sense of generic user input.
 *
 */

//=============================================================================
// ** NOTICE **
//-----------------------------------------------------------------------------
// The code below is generated by a compiler, and is not well suited for human
// reading. If you are interested on the source code, please take a look at
// the Github repository for this plugin!
//=============================================================================
